categorical_features:
  - holiday
numerical_features:
  - temp
  - rain_1h
  - snow_1h
  - clouds_all
dummies_features:
  - weather_main_Clear
  - weather_main_Clouds
  - weather_main_Drizzle
  - weather_main_Fog
  - weather_main_Haze
  - weather_main_Mist
  - weather_main_Rain
  - weather_main_Smoke
  - weather_main_Snow
  - weather_main_Squall
  - weather_main_Thunderstorm
  - weather_description_SQUALLS
  - weather_description_Sky is Clear
  - weather_description_broken clouds
  - weather_description_drizzle
  - weather_description_few clouds
  - weather_description_fog
  - weather_description_freezing rain
  - weather_description_haze
  - weather_description_heavy intensity drizzle
  - weather_description_heavy intensity rain
  - weather_description_heavy snow
  - weather_description_light intensity drizzle
  - weather_description_light intensity shower rain
  - weather_description_light rain
  - weather_description_light rain and snow
  - weather_description_light shower snow
  - weather_description_light snow
  - weather_description_mist
  - weather_description_moderate rain
  - weather_description_overcast clouds
  - weather_description_proximity shower rain
  - weather_description_proximity thunderstorm
  - weather_description_proximity thunderstorm with drizzle
  - weather_description_proximity thunderstorm with rain
  - weather_description_scattered clouds
  - weather_description_shower drizzle
  - weather_description_shower snow
  - weather_description_sky is clear
  - weather_description_sleet
  - weather_description_smoke
  - weather_description_snow
  - weather_description_thunderstorm
  - weather_description_thunderstorm with drizzle
  - weather_description_thunderstorm with heavy rain
  - weather_description_thunderstorm with light drizzle
  - weather_description_thunderstorm with light rain
  - weather_description_thunderstorm with rain
  - weather_description_very heavy rain
time_cyclical:
  - hour
  - month
  - day_of_week
target:
  - traffic_volume