LinearRegression:
Ridge:
  alpha: [0.01, 0.1, 0.5, 0.9]
ElasticNet:
  alpha: [0.01, 0.1, 0.5, 0.9]
  l1_ratio: [0.1, 0.5, 0.9]
RandomForestRegressor:
  n_estimators: [50, 100, 200]
  max_depth: [5, 10, 15]
  min_samples_split: [2, 10]