LinearRegression:
  fit_intercept: [True]
Ridge:
  alpha: [0.01, 0.1, 0.5, 0.9]
ElasticNet:
  alpha: [0.01, 0.1, 0.5, 0.9]
  l1_ratio: [0.1, 0.5, 0.9]
RandomForestRegressor:
  n_estimators: [100, 200, 300]
  max_depth: [5, 10, 15, 20]
  min_samples_split: [2, 7, 10, 15]